plugins {
    id 'java'
}

group = 'co.com.saucedemo'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation("org.seleniumhq.selenium:selenium-java:4.44.0")
    implementation("io.cucumber:cucumber-java:7.34.3")
    testImplementation("io.cucumber:cucumber-junit:7.34.3")
    testImplementation platform('io.cucumber:cucumber-bom:7.20.1')
    testImplementation platform('org.junit:junit-bom:5.11.0')
    testImplementation 'io.cucumber:cucumber-java'
    testImplementation 'io.cucumber:cucumber-junit-platform-engine'
    testImplementation 'org.junit.platform:junit-platform-suite'
    implementation 'com.aventstack:extentreports:5.1.1'

    implementation 'com.microsoft.playwright:playwright:1.49.0'
}

test {
    useJUnitPlatform()
}